### PR TITLE
Reinstate aoColumns so that we have proper sorting in percent columns

### LINKED ISSUE #79: Wrong sorting for coverage
It seems that coverage percents aren't correctly sorted according to their float value but rather treated as strings as reported over here: https://github.com/colszowka/simplecov/issues/781#issuecomment-572010578

example wrong sorting

we should fix that :)

### PR DESCRIPTION
**Pull request by PragTob**
Regression from first release.

See: https://github.com/colszowka/simplecov-html/commit/bc11506aa8d09126034a609e157df27bdfb70d1c#r36735556
Thanks @dmitry

Fixes #79

Sorry for the noise of the slight changes in the other parts of
the JS, VSCode made a decision and I was too lazy to go back
and make it a separate commit. :see-no-evil:

Relevant code is in layout.erb and the top of application.js
(where there's new code)

https://github.com/colszowka/simplecov/issues/781

### CODE REVIEW

File: assets/javascripts/application.js [hunk 1]
```diff
@@ -2,25 +2,33 @@
 //= require_directory ./plugins/
 //= require_self
 
-$(document).ready(function() {
+$(document).ready(function () {
+  branchCoverageActivated = $("body").data("branch-coverage") == true;
+
   // Configuration for fancy sortable tables for source file groups
```
Comment (klyonrad) [inline assets/javascripts/application.js]: Is this comment still useful?

File: assets/javascripts/application.js [hunk 2]
```diff
@@ -2,25 +2,33 @@
...
+  lineColumns = [null, { "sType": "percent" }, null, null, null, null, null];
+  branchColumns = [{ "sType": "percent" }, null, null, null];
```
Comment (klyonrad) [inline assets/javascripts/application.js]: Why does only one column get the type defined? If there is a reason it would be good to document it

Comment (dmitry) [reply assets/javascripts/application.js]: That's because branch columns has only one (first one) column with percentage, other ones are just counters: https://github.com/colszowka/simplecov-html/blob/master/views/file_list.erb#L67

Comment (dmitry) [reply assets/javascripts/application.js]: Might be good to comment here to look into the "file_list.erb" to checkout which columns are used there.

File: assets/javascripts/application.js (hunk 1 above)
Comment (PragTob) [reply assets/javascripts/application.js]: kinda at least I think so :D

File: assets/javascripts/application.js (hunk 2 above)
Comment (PragTob) [reply assets/javascripts/application.js]: Yeah good idea, I might have a look at jquery data tables if we could give the others a type or at least document that null has correct count/integer sorting. Good spot!

Comment (PragTob) [reply assets/javascripts/application.js]: Our datatables version is from... 2010. I can't find a manual/reference with a quick look and it's probably not worth a long look.
